@startuml
skinparam class {
    BackgroundColor white
    BorderColor black
    ArrowColor black
}

interface IWifiRepository <<interface>>{
    fetchWifiList(): Future<Either<IFailure, List>>
    connectToWifi(String ssid, String password): Future<Either<IFailure, Null>>
}

class WifiRepository <<class>>{
    fetchWifiList(): Future<Either<IFailure, List>>
    connectToWifi(String ssid, String password): Future<Either<IFailure, Null>>
}

package WifiConfiguration2 <<Folder>>{
}

WifiRepository .up.|> IWifiRepository
WifiRepository -right-> WifiConfiguration2

hide members
hide circle
show WifiRepository methods
show IWifiRepository methods

@enduml