@startuml

skinparam state {
  BackgroundColor White
  BorderColor Black
  ArrowColor Black
}

mainframe State: Wifi

[*] -right-> WifiInitial
WifiInitial -down-> WifiListLoading: FetchData event
WifiListLoading -right-> WifiListLoaded: WifiList not empty
WifiListLoaded -left-> WifiListLoading: FetchData event
WifiListLoading -left-> WifiListError: WifiList empty
WifiListError -right-> WifiListLoading: FetchData event 
WifiListLoaded -down-> WifiConnecting: ConnectToNetwork event
WifiConnecting -down-> WifiConnected: Wifi connection success
WifiConnecting -left-> WifiConnectionError: Wifi connection fail
WifiConnectionError -right-> WifiConnecting: ConnectToNetwork event
WifiConnectionError -up-> WifiListLoading: FetchData event
WifiConnected -left-> [*]: Navigate to another screen

WifiListLoading: Show loading spinner
WifiListLoading: Fetch WifiList

WifiListError: Show empty list WifiConnectionError

WifiListLoaded: Display WifiList

WifiConnectionError: Show connection to wifi failed

WifiConnecting: Connect to chosen Wifi

@enduml