@startuml

skinparam state {
  BackgroundColor White
  BorderColor Black
  ArrowColor Black
}

mainframe State: Wifi

[*] -right-> WifiInitial
WifiInitial -down-> WifiLoading: FetchData event
WifiLoading -right-> WifiLoaded: WifiList not empty
WifiLoaded -left-> WifiLoading: FetchData event
WifiLoading -left-> WifiListError: WifiList empty
WifiListError -right-> WifiLoading: FetchData event 
WifiLoaded -down-> WifiConnecting: ConnectToNetwork event
WifiConnecting -down-> WifiConnected: Wifi connection success
WifiConnecting -left-> WifiConnectionError: Wifi connection fail
WifiConnectionError -right-> WifiConnecting: ConnectToNetwork event
WifiConnectionError -up-> WifiLoading: FetchData event
WifiConnected -left-> [*]: Navigate to another screen

WifiLoading: Show loading spinner
WifiLoading: Fetch WifiList

WifiListError: Show empty list WifiConnectionError

WifiLoaded: Display WifiList

WifiConnectionError: Show connection to wifi failed

WifiConnecting: Connect to chosen Wifi

@enduml